In [1]:
import pandas as pd

In [2]:
df_data_without_watchers_outliers = pd.read_csv('data/data_cleaned/data_without_watchers_outliers_2023_05.csv')
df_watchers_outlires = pd.read_csv('data/data_cleaned/watchers_outliers_2023_05.csv')

contributors = pd.read_csv('data/data_cleaned/repo_contributors_05.csv')

data_c = pd.concat([df_data_without_watchers_outliers,df_watchers_outlires])

#data_c['full_name'].drop_duplicates(data_c['full_name'].index,inplace=True)
data_c.drop(columns=['Unnamed: 0.1','Unnamed: 0'],inplace=True)

#data_c['license'].replace('No License',{'key': 0,'name': 'No License','spdx_id': '','url': '','node_id': ''},inplace=True)

data_c.drop_duplicates(inplace=True)
#data_c.info()

In [3]:
#Replace No License to dict
data_c['license'].replace('No License',str(dict(key= '',name= 'No License',spdx_id= '',url= '',node_id= '')),inplace=True)

<h4>Technologies</h4>

In [4]:
technoligies = pd.DataFrame(list(data_c['language'].unique())).rename(columns={0:'name'})
techs = []
for index,tech in technoligies.iterrows():
    techs.append(dict(id=index+1,name=tech['name']))

technoligies = pd.DataFrame(techs)
technoligies

      id              name
0      1               C++
1      2            Kotlin
2      3  Jupyter Notebook
3      4              Java
4      5        TypeScript
..   ...               ...
183  184          Bikeshed
184  185             Smali
185  186       Vim Snippet
186  187              YARA
187  188                Hy

[188 rows x 2 columns]

<h4>Owners</h4>

In [5]:
owners = pd.DataFrame(list(data_c['type'].unique())).rename(columns={0:'name'})
ors = []
for index,otype in owners.iterrows():
    ors.append(dict(id=index+1,name=otype['name']))

owners = pd.DataFrame(ors)
owners

   id          name
0   1          User
1   2  Organization

<h4>License</h4>

In [6]:
import ast

#table license
licenses = pd.DataFrame(list(data_c['license'].unique())).rename(columns={0:'name'})
lics = []
for index,l in licenses.iterrows():
    lics.append(ast.literal_eval(l['name']))


licenses = pd.DataFrame(lics)
licenses.insert(0,"id", list(range(1,len(lics)+1)),True)
licenses

,id,key,name,spdx_id,url,node_id
0,1,,No License,,,
1,2,gpl-3.0,GNU General Public License v3.0,GPL-3.0,https://api.github.com/licenses/gpl-3.0,MDc6TGljZW5zZTk=
2,3,mit,MIT License,MIT,https://api.github.com/licenses/mit,MDc6TGljZW5zZTEz
3,4,agpl-3.0,GNU Affero General Public License v3.0,AGPL-3.0,https://api.github.com/licenses/agpl-3.0,MDc6TGljZW5zZTE=
4,5,0bsd,BSD Zero Clause License,0BSD,https://api.github.com/licenses/0bsd,MDc6TGljZW5zZTM1
5,6,bsd-3-clause,"BSD 3-Clause ""New"" or ""Revised"" License",BSD-3-Clause,https://api.github.com/licenses/bsd-3-clause,MDc6TGljZW5zZTU=
6,7,mit-0,MIT No Attribution,MIT-0,https://api.github.com/licenses/mit-0,MDc6TGljZW5zZTQx
7,8,other,Other,NOASSERTION,None,MDc6TGljZW5zZTA=
8,9,apache-2.0,Apache License 2.0,Apache-2.0,https://api.github.com/licenses/apache-2.0,MDc6TGljZW5zZTI=
9,10,lgpl-3.0,GNU Lesser General Public License v3.0,LGPL-3.0,https://api.github.com/licenses/lgpl-3.0,MDc6TGljZW5zZTEy
10,11,gpl-2.0,GNU General Public License v2.0,GPL-2.0,https://api.github.com/licenses/gpl-2.0,MDc6TGljZW5zZTg=
11,12,cc0-1.0,Creative Commons Zero v1.0 Universal,CC0-1.0,https://api.github.com/licenses/cc0-1.0,MDc6TGljZW5zZTY=
12,13,lgpl-2.1,GNU Lesser General Public License v2.1,LGPL-2.1,https://api.github.com/licenses/lgpl-2.1,MDc6TGljZW5zZTEx
13,14,cc-by-4.0,Creative Commons Attribution 4.0 International,CC-BY-4.0,https://api.github.com/licenses/cc-by-4.0,MDc6TGljZW5zZTI1
14,15,unlicense,The Unlicense,Unlicense,https://api.github.com/licenses/unlicense,MDc6TGljZW5zZTE1
15,16,isc,ISC License,ISC,https://api.github.com/licenses/isc,MDc6TGljZW5zZTEw
16,17,bsd-2-clause,"BSD 2-Clause ""Simplified"" License",BSD-2-Clause,https://api.github.com/licenses/bsd-2-clause,MDc6TGljZW5zZTQ=
17,18,zlib,zlib License,Zlib,https://api.github.com/licenses/zlib,MDc6TGljZW5zZTI3
18,19,mpl-2.0,Mozilla Public License 2.0,MPL-2.0,https://api.github.com/licenses/mpl-2.0,MDc6TGljZW5zZTE0
19,20,epl-2.0,Eclipse Public License 2.0,EPL-2.0,https://api.github.com/licenses/epl-2.0,MDc6TGljZW5zZTMy
20,21,bsd-4-clause,"BSD 4-Clause ""Original"" or ""Old"" License",BSD-4-Clause,https://api.github.com/licenses/bsd-4-clause,MDc6TGljZW5zZTM5
21,22,osl-3.0,Open Software License 3.0,OSL-3.0,https://api.github.com/licenses/osl-3.0,MDc6TGljZW5zZTE2
22,23,mulanpsl-2.0,"Mulan Permissive Software License, Version 2",MulanPSL-2.0,https://api.github.com/licenses/mulanpsl-2.0,L_kgCsbXVsYW5wc2wtMi4w
23,24,wtfpl,Do What The F*ck You Want To Public License,WTFPL,https://api.github.com/licenses/wtfpl,MDc6TGljZW5zZTE4
24,25,cc-by-sa-4.0,Creative Commons Attribution Share Alike 4.0 I...,CC-BY-SA-4.0,https://api.github.com/licenses/cc-by-sa-4.0,MDc6TGljZW5zZTI2
25,26,bsl-1.0,Boost Software License 1.0,BSL-1.0,https://api.github.com/licenses/bsl-1.0,MDc6TGljZW5zZTI4
26,27,upl-1.0,Universal Permissive License v1.0,UPL-1.0,https://api.github.com/licenses/upl-1.0,MDc6TGljZW5zZTMz
27,28,lppl-1.3c,LaTeX Project Public License v1.3c,LPPL-1.3c,https://api.github.com/licenses/lppl-1.3c,MDc6TGljZW5zZTIz
28,29,ncsa,University of Illinois/NCSA Open Source License,NCSA,https://api.github.com/licenses/ncsa,MDc6TGljZW5zZTI5
29,30,bsd-3-clause-clear,BSD 3-Clause Clear License,BSD-3-Clause-Clear,https://api.github.com/licenses/bsd-3-clause-c...,MDc6TGljZW5zZTIx
30,31,epl-1.0,Eclipse Public License 1.0,EPL-1.0,https://api.github.com/licenses/epl-1.0,MDc6TGljZW5zZTc=
31,32,cern-ohl-w-2.0,CERN Open Hardware Licence Version 2 - Weakly ...,CERN-OHL-W-2.0,https://api.github.com/licenses/cern-ohl-w-2.0,L_kgCuY2Vybi1vaGwtdy0yLjA
32,33,cern-ohl-p-2.0,CERN Open Hardware Licence Version 2 - Permissive,CERN-OHL-P-2.0,https://api.github.com/licenses/cern-ohl-p-2.0,L_kgCuY2Vybi1vaGwtcC0yLjA
33,34,artistic-2.0,Artistic License 2.0,Artistic-2.0,https://api.github.com/licenses/artistic-2.0,MDc6TGljZW5zZTM=
34,35,ofl-1.1,SIL Open Font License 1.1,OFL-1.1,https://api.github.com/licenses/ofl-1.1,MDc6TGljZW5zZTE3
35,36,odbl-1.0,Open Data Commons Open Database License v1.0,ODbL-1.0,https://api.github.com/licenses/odbl-1.0,MDc6TGljZW5zZTM3
36,37,eupl-1.2,European Union Public License 1.2,EUPL-1.2,https://api.github.com/licenses/eupl-1.2,MDc6TGljZW5zZTM0

<h4>Contributors</h4>

In [7]:
cs = pd.DataFrame(contributors['name'].unique()).rename(columns={0:'name'})

cs.insert(0,'id',range(1,len(cs)+1),True)

cs

          id             name
0          1            biuuu
1          2            cntvc
2          3  TremblingMoeNew
3          4       LaiYueTing
4          5          vdohney
...      ...              ...
12566  12567            nijuy
12567  12568         jingliu9
12568  12569          RogerPu
12569  12570           tumGER
12570  12571   NicholeMattera

[12571 rows x 2 columns]

<h4>Repositories</h4>

In [8]:
repositories = pd.DataFrame(data_c['full_name'].unique()).rename(columns={0:'full_name'})

repositories.insert(0,'id',range(1,len(repositories)+1),True)
repositories

          id                               full_name
0          1            477132016yb/plant-vs-zombies
1          2       ParveshSandila/CountryCodeChooser
2          3  ozodbek-sobirjonovich/sqlite3_tutorial
3          4                          mahomaps/mm-v1
4          5              cruip/cruip-tutorials-next
...      ...                                     ...
25485  25486                  gptlink/gptlink-deploy
25486  25487    akashusr/assignment-solution-batch-2
25487  25488                  smile1130/laravel9_CMS
25488  25489                  asaotomo/makephonedict
25489  25490                   ACodeDaily/AcodeDaily

[25490 rows x 2 columns]

In [9]:
dataToInserted = data_c

#--Replace technologies
for index,tech in technoligies.iterrows():
    dataToInserted['language'].replace(tech['name'],tech['id'],inplace=True)


#--Replace owners
for index,tech in owners.iterrows():
    dataToInserted['type'].replace(tech['name'],tech['id'],inplace=True)

dataToInserted.head(2)

,full_name,url,clone_url,watchers_count,stargazers_count,language,forks,description,type,license,fork,created_at,updated_at,pushed_at
0,477132016yb/plant-vs-zombies,https://github.com/477132016yb/plant-vs-zombies,https://github.com/477132016yb/plant-vs-zombie...,12,12,1,0,NaN,1,"{'key': '', 'name': 'No License', 'spdx_id': '...",False,2023-05-01,2023-06-15,2023-06-13
1,ParveshSandila/CountryCodeChooser,https://github.com/ParveshSandila/CountryCodeC...,https://github.com/ParveshSandila/CountryCodeC...,12,12,2,1,Country code chooser in Jetpack compose,1,"{'key': '', 'name': 'No License', 'spdx_id': '...",False,2023-05-01,2023-06-06,2023-06-09

In [10]:
#--Replace license
for index,l in licenses.iterrows():
    #print(str(dict(l[['key','name','spdx_id','url','node_id']])))
    dataToInserted['license'].replace(str(dict(l[['key','name','spdx_id','url','node_id']])),l['id'],inplace=True)

#dataToInserted[dataToInserted['license'] == str(dict(licenses[['key','name','spdx_id','url','node_id']].head(1)))]

#dict(licenses[['key','name','spdx_id','url','node_id']].head(1))
dataToInserted.head(2)

,full_name,url,clone_url,watchers_count,stargazers_count,language,forks,description,type,license,fork,created_at,updated_at,pushed_at
0,477132016yb/plant-vs-zombies,https://github.com/477132016yb/plant-vs-zombies,https://github.com/477132016yb/plant-vs-zombie...,12,12,1,0,NaN,1,1,False,2023-05-01,2023-06-15,2023-06-13
1,ParveshSandila/CountryCodeChooser,https://github.com/ParveshSandila/CountryCodeC...,https://github.com/ParveshSandila/CountryCodeC...,12,12,2,1,Country code chooser in Jetpack compose,1,1,False,2023-05-01,2023-06-06,2023-06-09

In [11]:
# add id to each repos
#add columns ID
dataToInserted['id'] = dataToInserted['full_name']

for index, r in repositories.iterrows():
    dataToInserted['id'].replace(r['full_name'],r['id'],inplace=True)

In [12]:
dataToInserted.to_csv('dataToInserted.csv')

<h2>L'insertion des donnÃ©es en base de donnÃ©es<h2>

In [12]:
import pyodbc

cnxn = pyodbc.connect('Driver={SQL Server};'
                      'Server=LAPTOP-B5O30HDH\SQLEXPRESS;'
                      'Database=githubdb;'
                      'Trusted_Connection=yes;')

<h3>Technologies</h3>

In [16]:
cursor = cnxn.cursor()

for index,tech in technoligies.iterrows():
    cursor.execute('INSERT INTO technologies (name) values (?)',tech['name'])

cursor.commit()
cursor.close()

<h3>Owners</h3>

In [17]:
cursor = cnxn.cursor()

for index, owner in owners.iterrows():
    cursor.execute('INSERT INTO owners (type) values (?)',owner['name'])
cursor.commit()
cursor.close()

<h3>Licenses</h3>

In [18]:


cursor = cnxn.cursor()

for index, lic in licenses.iterrows():
    cursor.execute("INSERT INTO licenses (lkey,name,url,spdxID,nodeID) values (?,?,?,?,?)",lic['key'],lic['name'],lic['spdx_id'],lic['url'],lic['node_id'])
cursor.commit()
cursor.close()

<h4>Contributors</h4>

In [19]:
cursor = cnxn.cursor()

for index, c in contributors.iterrows():
    cursor.execute("INSERT INTO contributors (name) values (?)",c['name'])
cursor.commit()
cursor.close()

In [27]:
dataToInserted.head()

,full_name,url,clone_url,watchers_count,stargazers_count,language,forks,description,type,license,fork,created_at,updated_at,pushed_at,id
0,477132016yb/plant-vs-zombies,https://github.com/477132016yb/plant-vs-zombies,https://github.com/477132016yb/plant-vs-zombie...,12,12,1,0,No Description,1,1,False,2023-05-01,2023-06-15,2023-06-13,1
1,ParveshSandila/CountryCodeChooser,https://github.com/ParveshSandila/CountryCodeC...,https://github.com/ParveshSandila/CountryCodeC...,12,12,2,1,Country code chooser in Jetpack compose,1,1,False,2023-05-01,2023-06-06,2023-06-09,2
2,ozodbek-sobirjonovich/sqlite3_tutorial,https://github.com/ozodbek-sobirjonovich/sqlit...,https://github.com/ozodbek-sobirjonovich/sqlit...,12,12,3,0,No Description,1,1,False,2023-05-01,2023-06-10,2023-05-01,3
3,mahomaps/mm-v1,https://github.com/mahomaps/mm-v1,https://github.com/mahomaps/mm-v1.git,12,12,4,2,MahoMaps: Yandex.Maps client for MIDP2,2,2,False,2023-05-01,2023-06-04,2023-06-18,4
4,cruip/cruip-tutorials-next,https://github.com/cruip/cruip-tutorials-next,https://github.com/cruip/cruip-tutorials-next.git,12,12,5,4,A repository of Cruip's guides & tutorials mad...,2,1,False,2023-05-01,2023-06-18,2023-06-18,5

<h4>Repositories</h4>

In [13]:
dataToInserted['description'].fillna('No Description',inplace=True)
#dataToInserted['description'].isnull().sum()

In [14]:
cursor = cnxn.cursor()

for index, d in dataToInserted.iterrows():
    #print(d['full_name'],d['description'],d['url'],d['clone_url'],d['fork'],d['watchers_count'],d['forks'],d['created_at'],d['updated_at'],d['pushed_at'],d['language'],d['type'],d['license'])
    cursor.execute("INSERT INTO repositories (fullName,description,url,cloneUrl,watchersCount,forks,createdAt,updatedAt,pushedAt,langID,ownerID,licenseID) values (?,?,?,?,?,?,?,?,?,?,?,?)",d['full_name'],d['description'],d['url'],d['clone_url'],d['watchers_count'],d['forks'],d['created_at'],d['updated_at'],d['pushed_at'],d['language'],d['type'],d['license'])
cursor.commit()
cursor.close()

<h4>Commits</h4>

In [15]:
#commits = dataToInserted[['id','full_name',]]

commits = contributors[['full_name','name','commits']]

#replace name contributors by id
for index, c in cs.iterrows():
    commits['name'].replace(c['name'],c['id'],inplace=True)

C:\Users\Youcode\AppData\Local\Temp\ipykernel_14064\542819858.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  commits['name'].replace(c['name'],c['id'],inplace=True)

In [17]:
#replace name contributors by id
for index, c in repositories.iterrows():
    commits['full_name'].replace(c['full_name'],c['id'],inplace=True)

C:\Users\Youcode\AppData\Local\Temp\ipykernel_14064\3544187285.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  commits['full_name'].replace(c['full_name'],c['id'],inplace=True)

In [24]:
commits = pd.read_csv('commits.csv',index_col=0)

commits['full_name'].astype('int')
commits['name'].astype('int')

commits

       full_name   name  commits
0          22222      1       38
1          22222      2        1
2          22222      3        1
3          22222      4        1
4          22223      5       25
...          ...    ...      ...
13914      14805  12567      240
13915      14806  12568       14
13916      14807  12569       13
13917      14808  12570       25
13918      14808  12571       19

[13811 rows x 3 columns]

In [ ]:
cursor = cnxn.cursor()
for row in commits.itertuples():
    cursor.execute(
        f'''INSERT INTO CommitsVALUES (?,?,?)''',
        row.full_name,
        row.name,
        row.commits
    )
cursor.commit()
cursor.close()